---
sudo: required
language: python
python: "2.7"
services:
  - docker
env:
  - distribution: centos
    version: 7
    java_major: 8
    java_minor: 172
  - distribution: ubuntu
    version: artful
    java_major: 10
    java_minor: 1
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y python-pip libssl-dev
  - pip install docker-py
  - /usr/bin/env
install:
  - pip install molecule==2.5.0
  - pip install ansible==2.4.0
  - ansible --version
  - molecule --version
  - py.test --version

script:
  - molecule test
