---
sudo: required
language: python
python: "2.7"
services:
  - docker
env:
  - DISTRIBUTION: centos
    VERSION: 7
  - DISTRIBUTION: centos
    VERSION: 6
  - DISTRIBUTION: ubuntu
    VERSION: artful
  - DISTRIBUTION: ubuntu
    VERSION: trusty
  - DISTRIBUTION: ubuntu
    VERSION: xenial
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y python-pip libssl-dev
  - pip install docker-py
  - /usr/bin/env
install:
  - pip install molecule==2.13.1
  - pip install ansible==2.4.4
  - ansible --version
  - molecule --version
  - py.test --version

script:
  - molecule test
