---

- name: Fail if link is not provided
  fail:
    msg: 'Set java_install_link for link install mode please.'
  when: 'java_install_link == ""'

- name: Set all required facts
  set_fact:
    java_tar_name: "jdk-{{ java_major_version }}u{{ java_minor_version }}.tar.gz"

- name: Download TAR archive from direct link.
  get_url:
    url: "{{ java_install_link }}"
    dest: "{{ java_distr_path }}/{{ java_tar_name }}"
    force: no
    validate_certs: no
    timeout: 600
