---

- block:

    - name: 'Check permissions.'
      file:
        path: '{{ java_home }}'
        mode: 'u+rwX,g+rX,o+rX'
        state: 'directory'
        recurse: true

    - name: 'Ensure that java installed via alternatives.'
      alternatives:
        name: 'java'
        link: '/usr/bin/java'
        path: '{{ java_home }}/bin/java'

    - name: 'Ensure that correct java version is selected.'
      alternatives:
        name: 'java'
        path: '{{ java_home }}/bin/java'

    - name: 'Set JAVA_HOME.'
      lineinfile:
        dest: '/etc/environment'
        state: 'present'
        regexp: '^JAVA_HOME'
        line: 'JAVA_HOME="{{ java_home }}"'
      when: 'java_set_home'

  become: true
