---
# file: tasks/install.yml

- name: download tar archive from oracle site
  get_url:
    url: "{{ jarTarURL }}"
    headers: "Cookie:oraclelicense=accept-securebackup-cookie"
    dest: "{{ javaDownloadPath }}/{{ jdkTarName }}"
    force: no
    validate_certs: no
    timeout: 600
  when: javaFromOracle and not oracleAuth

- name: download tar archive from oracle site with Oracle Account ID
  get_url:
    url: "{{ jarTarURL }}"
    headers: "Cookie:oraclelicense=accept-securebackup-cookie"
    dest: "{{ javaDownloadPath }}/{{ jdkTarName }}"
    force: no
    force_basic_auth: yes
    url_username: '{{ oracleIDUsername }}'
    url_password: '{{ oracleIDPassword }}'
    validate_certs: no
    timeout: 600
  when: javaFromOracle and oracleAuth

- name: copy tar archive from local
  copy:
    src: "{{ jdkTarName }}"
    dest: "{{ javaDownloadPath }}/{{ jdkTarName }}"
  when: not javaFromOracle

- name: unarchive tar archive with JDK
  unarchive:
    src: "{{ javaDownloadPath }}/{{ jdkTarName }}"
    dest: "{{ javaPath }}"
    copy: no
    creates: '{{ jdkHome }}/{{ jdkVersion }}'

- name: remove downloaded file
  file:
    path: "{{ javaDownloadPath }}/{{ jdkTarName }}"
    state: absent
  when: javaClearAfter
