---

- name: Set all required facts.
  import_tasks: set-facts.yml

- name: Prepare instance.
  import_tasks: prepare.yml

- name: Install Oracle JDK.
  import_tasks: install/main.yml
  when: not java_version_found

- name: Configure Oracle JDK.
  import_tasks: configure.yml
