---
# file: tasks/main.yml

- name: Check all required variables.
  import_tasks: check-vars.yml

- name: Set all required facts.
  import_tasks: set-facts.yml

- name: Prepare instance to provisioning.
  import_tasks: prepare.yml

- name: Install Oracle Jdk.
  include_tasks: install.yml
  when: not jdkVersionFound

- name: Configure Oracle Jdk.
  import_tasks: configure.yml
