---

- name: 'Check Mode.'
  fail:
    msg: "This mode is not supported"
  when: not (java_install_mode in java_install_modes)

- name: 'Check Version.'
  fail:
    msg: "This version is unavailable in oracle OTN PUB repository. Use another mode please."
  when: "(java_install_mode == 'oracle') or
         (java_major_version|int != 10 and java_minor_version != 1) or
         (java_major_version|int != 8 and java_minor_version < 171) or
         (java_major_version|int == 7)"

- name: Include OS Specific variables.
  include_vars: '{{ ansible_os_family }}.yml'

- name: Set initial variables.
  set_fact:
    java_version_found: false

- name: Set other variables (8.x)
  set_fact:
    java_version: "1.{{ java_major_version }}.0_{{ java_minor_version }}"
    java_home: "{{ java_home | default ( java_root_path + '/jdk1.' + java_major_version|string + '.0_' + java_minor_version|string ) }}"
  when: java_major_version|int == 8

- name: Set other variables (10.x)
  set_fact:
    java_version: "jdk-{{ java_major_version }}.0.{{ java_minor_version }}"
    java_home: "{{ java_home | default ( java_root_path + '/jdk-' + java_major_version|string + '.0.' + java_minor_version|string ) }}"
  when: java_major_version|int == 10
