---
# file: roles/oracle-java/vars/java-builds.yml

javaBuilds:
  8:
    121: 
      'build': 13
      'downloadId': 'e9e7ea248e2c4826b92b3f075a80e441'
    112: 
      'build': 15
    111: 
      'build': 14
    102: 
      'build': 14
    101: 
      'build': 13
    91: 
      'build': 14
    92: 
      'build': 14
    77: 
      'build': 03
    74: 
      'build': 02
    73: 
      'build': 02
    72: 
      'build': 15
    66: 
      'build': 17
    65: 
      'build': 17
    60: 
      'build': 27
    51: 
      'build': 16
    45: 
      'build': 14
    31: 
      'build': 13
  7:
    80: 
      'build': 15
    79: 
      'build': 15
    75: 
      'build': 13