---

- name: 'Destroy Docker instances for common role'
  hosts: 'localhost'
  connection: 'local'
  gather_facts: false
  vars:
    molecule_yml: '{{ lookup("file", molecule_file) | from_yaml }}'

  tasks:

    - name: 'Destroy molecule instance(s)'
      docker_container:
        name: '{{ item.name }}'
        state: 'absent'
      with_items: '{{ molecule_yml.platforms }}'
